minima:
  skin: dark
  show_excerpts: true
  date_format: "%Y.%m.%d %H:%M"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  # date_format: "%b %-d, %Y"

remote_theme: "jekyll/minima"
